[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#585b70"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#f5c2e7"
text = "#1e1e2e"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.selection]
background = "#f5c2e7"
text = "#1e1e2e"

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"
WINIT_UNIX_BACKEND = "x11"

[font]
size = 23

[font.bold]
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCodeNerdFontMono"
style = "Medium"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[terminal]

[scrolling]
history = 10000
multiplier = 3

#[terminal.shell]
#args = ["new-session", "-A", "-s", "main"]
#program = "/usr/bin/tmux"

[window]
blur = true
decorations = "none"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.padding]
x = 8
y = 6

[keyboard]
